volumes:
  db_postgres:

services:

  db:
    container_name: postgres-nest-graphql
    image: postgres
    restart: always
    ports:
      - "4321:4321"
    environment:
      POSTGRES_DB: postgres-graphql
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_postgres:/var/lib/postgresql/data