volumes:
  db_postgres:

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - db_postgres:/var/lib/postgresql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql