CREATE DATABASE postgres_graphql;

CREATE TABLE public.user (
    id_usuario bigint NOT NULL,
    nome text NOT NULL,
    email text NOT NULL,
    profissao text NOT NULL,
    organizacao text NOT NULL,
    atuacao text NOT NULL,
    verificado boolean DEFAULT false NOT NULL
);

ALTER TABLE public.user ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);